### ISSUE TITLE
 bokeh.models.tools.tool_events  has been deprecated

### ISSUE THREAD

**Issue by FrancescaTaddei** [ChairOfStructuralMechanicsTUM/Mechanics_Apps#20]
For the new Bokeh version 0.12.10, 

> bokeh.models.tools.tool_events

 has been deprecated. We should use the SelectionGeometry event present on Plot or Figure. https://bokeh.pydata.org/en/latest/docs/releases/0.12.7.html

This is a Problem in `Pendulum` and `Collision` and `Conservation_angular_momentum`
![grafik](https://user-images.githubusercontent.com/25368100/32062579-2cee338e-ba75-11e7-9535-7d8eab4abefd.png)

@qaumann, could you try to fix this in `Pendulum` and then communicate the solution to @moustafabachar for ` Collision` and `Conservation_angular_momentum`
Thanks

**Comment by qaumann** [comment]
The issue has been fixed for the `Pendulum` app, please see 712bf197d96852219f854e7c44a176a9bc3a880f. The bokeh documentation about the different event types (https://bokeh.pydata.org/en/latest/docs/reference/events.html) can be helpful selecting the suitable event.

**Comment by FrancescaTaddei** [comment]
`Pendulum` is fixed.
`Collision` is fixed.
Please @moustafabachar fix also `Conservation_angular_momentum`.
Thanks

**Comment by FrancescaTaddei** [comment]
`Pendulum` not fixed!
![unbenannt](https://user-images.githubusercontent.com/25368100/32366958-b030b5e4-c080-11e7-949c-2fe8852abd31.JPG)
@qaumann

**Comment by FrancescaTaddei** [comment]
`Pendulum` fixed!
Thanks @qaumann
